
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zloqccxqgatkpnngeqbq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpsb3FjY3hxZ2F0a3BubmdlcWJxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2MzA5NjcsImV4cCI6MjA2NDIwNjk2N30.S2lE3tTqtW4AI8ER7BxWeXvYe56p7YEFPKQrG8WYcks";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Import mobile utilities
import { createMobileStorage, isMobileDevice } from '@/utils/mobileAuthUtils';

// Create mobile-friendly storage
const authStorage = typeof window !== 'undefined' 
  ? (isMobileDevice() ? createMobileStorage() : window.localStorage)
  : undefined;

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: authStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce',
    // Add mobile-specific settings
    ...(isMobileDevice() && {
      storageKey: 'sb-auth-token',
      debug: false,
    })
  },
  global: {
    headers: {
      'X-Client-Info': 'supabase-js-web'
    }
  }
});
